spring:
  application:
    name: hodei-notifications
  cloud:
    stream:
      function:
        definition: processNotification
      bindings:
        processNotification-in-0:
          destination: hodei-notifications
          group: process
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            retryable-exceptions:
              javax:
                validation:
                  #ValidationException: true
                  ConstraintViolationException: false

  data:
    mongodb:
      database: hodei-notifications
      port: 27017
      host: localhost

  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      auth: true
      protocol: smtp
      debug: false

logging:
  level:
    root: info
    org.springframework.data: warn
    org.github.labcabrera: debug

app:
  notifications:
    mail:
      from: test-notifications@cnppartners.eu
    telegram:
      token: ${TELEGRAM_TOKEN}
      chat-id: -330068436
      url: https://api.telegram.org/bot${app.notifications.telegram.token}/sendMessage
